### ISSUE TITLE
No content for reverse proxy

### ISSUE THREAD

**Issue by CrysK** [mthenw/frontail#256]
Hello all, 

I have set up frontail in docker. When I call the internal IP with port, then the web page appears without error.
If I forward this page via reverse proxy, the page appears but the content is empty. 

The debugger displays: 

`Firefox cannot connect to the server at wss:/example.com/socket.io/?EIO=3&transport=websocket.`
`GET	wss://example.com/socket.io/?EIO=3&transport=websocket`
Status is: `blocked`

What's going wrong? 

Here are my settings:

`docker-compose.yml`:
```
version: '3.9'

services:
  frontail:
    image: mthenw/frontail:4.9.2
    container_name: frontail
    restart: unless-stopped
    volumes:
      - /var/log:/log:ro
    ports:
      - 8093:9001
    command: >
      /log/syslog
``` 

`/etc/apache2/sites-available/030-frontail.conf`:
``` 
<VirtualHost *:80>
	ServerName example.com
	ProxyPreserveHost On
	ProxyPass / http://127.0.0.1:8093/
	ProxyPassReverse / http://127.0.0.1:8093/
</VirtualHost>
```

Thanks a lot
