### ISSUE TITLE
Highlight messages according to different log files

### ISSUE THREAD

**Issue by chetanpatil1984** [mthenw/frontail#98]
Can you please add feature where we can specify the message color per log file. That is, messages coming from x.log should be displayed in blue, messages coming from y.log should be displayed in green.

Thanks.

**Comment by yaruson** [comment]
I guess it might be better to distribute log files across different tabs, and leave highlighting to various levels of log entries.

**Comment by Rom1deTroyes** [comment]
I know it's an old issue, but something like docker-compose colors logs would be wonderfull !

Maybe catching the `==> /pathto/file.log <==` and transform this to a line prefix with color ?

![image](https://user-images.githubusercontent.com/8625432/69867351-cbb92100-12a6-11ea-9fb0-2b3d76c36dc8.png)

A test for illustration : docker-compose.yaml

```yaml
version: '3'
services:

  tata:
    image: ubuntu:16.04
    command: sh -c 'echo \\033[31mhello ; sleep 3 ; echo \\033[32mworld ; sleep 1'

  toto:
    image: ubuntu:16.04
    command: sh -c 'echo \\033[31mhello ; sleep 1 ; echo \\033[32mworld ; sleep 3'
```
